{% set name = "sqlalchemy-hana" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-hana-{{ version }}.tar.gz
  sha256: e027f52977538cbc1b3e7f0adcf1531471adfe27a12fdc30d08f93f1e7a8da50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sqlalchemy >=1.0.0

test:
  imports:
    - sqlalchemy_hana
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SAP/sqlalchemy-hana/
  summary: SQLAlchemy dialect for SAP HANA
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swenger
    - janjagusch
