schema_version: 1

context:
  name: sqlalchemy-hana
  version: "3.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 37ea5033628e1682037dd13dc5b9e4c585dfa28bc2bdbc02f816059147262bae

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - sqlalchemy >=1.0.0
    - hdbcli >=2.19

tests:
  - python:
      imports:
        - sqlalchemy_hana
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: SQLAlchemy dialect for SAP HANA
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/SAP/sqlalchemy-hana/

extra:
  recipe-maintainers:
    - swenger
    - janjagusch
