schema_version: 1

context:
  name: sqlalchemy-hana
  version: "3.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: cf610807119f4bcea37612f06ecbe729b59c46ff7fea5c82b0528751009f6779

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - hdbcli
    - sqlalchemy >=1.0.0

tests:
  - python:
      imports:
        - sqlalchemy_hana
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: SQLAlchemy dialect for SAP HANA
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/SAP/sqlalchemy-hana/

extra:
  recipe-maintainers:
    - swenger
    - janjagusch
